import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/header/NavBar";
import Home from "./page";
import SubNavBar from "@/components/header/SubNavBar";
import VerticalLine from "@/components/UI/Figures/VerticalLine";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="relative min-h-screen">
        <NavBar />
        <SubNavBar />
        <Home />
        <VerticalLine left={15}/>
        <VerticalLine left={35}/>
        <footer className="bg-[#343338] text-white flex flex-row justify-between px-[30px] py-[25px] text-inter relative z-10">
          <img className="h-[16px] w-[" src="HandledLogo.png"/>
          <div className="text-center text-[16px]">
            <p>Home</p>
            <p>About Us</p>
            <p>Services</p>
            <p>Pricing</p>
            <p>Contact</p>
          </div>
          <div className="text-[12px] flex flex-col justify-between">
            <div>
              <p>T:013624829742</p>
              <p>email:</p>
              <p>handled@gmail.com</p>
            </div>
            <p>Privacy Policy</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
