import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/header/NavBar";
import Home from "./page";
import SubNavBar from "@/components/header/SubNavBar";
import VerticalLine from "@/components/VerticalLine";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="relative min-h-screen">
        <NavBar />
        <SubNavBar />
        <Home />
        <VerticalLine left={15}/>
        <VerticalLine left={35}/>
      </body>
    </html>
  );
}
